# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
