# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-06 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='urlimage',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='urlimage',
            field=models.URLField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='urlimage',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
