# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-09 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180506_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slashed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
